-- 코드를 입력하세요
WITH TBL AS(
    SELECT *,EXTRACT(YEAR FROM A.sales_date)AS YEAR, EXTRACT(MONTH FROM A.sales_date)AS MONTH
FROM ONLINE_SALE A LEFT OUTER JOIN USER_INFO B
USING (USER_ID)),

TBL2 AS(SELECT YEAR,MONTH,GENDER,COUNT(DISTINCT USER_ID) AS USERS
        FROM TBL
        GROUP BY YEAR,MONTH,GENDER)

SELECT *
FROM TBL2
WHERE GENDER IS NOT NULL
ORDER BY YEAR,MONTH,GENDER