-- 코드를 입력하세요
SELECT YEAR,MONTH,GENDER,COUNT(DISTINCT USER_ID)AS USERS

FROM(SELECT A.USER_ID,A.GENDER,EXTRACT(YEAR FROM SALES_DATE)AS YEAR,EXTRACT(MONTH FROM SALES_DATE)AS MONTH
FROM USER_INFO A RIGHT OUTER JOIN ONLINE_SALE B
ON A.USER_ID=B.USER_ID
WHERE GENDER IS NOT NULL)X

GROUP BY YEAR,MONTH,GENDER
ORDER BY YEAR,MONTH,GENDER


