-- 코드를 입력하세요
# 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 - OK
# 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고
# 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
WITH TBL AS(
SELECT car_id,history_id,MAX(START_DATE)AS START_DATE,MAX(END_DATE)AS END_DATE,car_type,daily_fee
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY LEFT OUTER JOIN CAR_RENTAL_COMPANY_CAR 
USING (CAR_ID)
WHERE (CAR_TYPE='세단'OR CAR_TYPE='SUV') 
GROUP BY CAR_ID),

TBL2 AS(
SELECT *
FROM TBL
WHERE START_DATE>='2022-12-01' OR END_DATE<='2022-10-31'),
TBL3 AS(
SELECT *
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
WHERE DURATION_TYPE='30일 이상' AND (CAR_TYPE='세단' OR CAR_TYPE='SUV' )),
TBL4 AS(
SELECT car_id,car_type,ROUND(daily_fee*((100-discount_rate)/100)*30,0) AS FEE
FROM TBL2 LEFT OUTER JOIN TBL3
USING (CAR_TYPE))

SELECT *
FROM TBL4
WHERE FEE>=500000 AND FEE<=2000000
ORDER BY FEE DESC,car_type,car_id DESC