-- 코드를 입력하세요
-- 코드를 입력하세요
WITH TBL AS(SELECT *
FROM CAR_RENTAL_COMPANY_CAR 
WHERE CAR_TYPE='세단'OR CAR_TYPE='SUV'),

TBL2 AS(SELECT car_id,DATE_FORMAT(MAX(start_date),'%Y-%m-%d')as START_DATE,DATE_FORMAT(MAX(END_DATE),'%Y-%m-%d')as END_DATE,CAR_TYPE,DAILY_FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A NATURAL JOIN TBL B
GROUP BY CAR_ID),

TBL3 AS (SELECT *
FROM TBL2
WHERE START_DATE > '2022-12-01' OR END_DATE < '2022-11-01'),

TBL4 AS(SELECT *
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
WHERE (CAR_TYPE='세단' OR CAR_TYPE='SUV')AND DURATION_TYPE='30일 이상'),

TBL5 AS(SELECT DISTINCT TBL3.CAR_ID,TBL3.CAR_TYPE, ROUND(30*DAILY_FEE*((100-DISCOUNT_RATE)/100),0)AS FEE
FROM TBL3 LEFT OUTER JOIN TBL4
ON TBL3.CAR_TYPE=TBL4.CAR_TYPE)

SELECT *
FROM TBL5
WHERE FEE >= 500000 AND FEE< 2000000
ORDER BY FEE DESC,CAR_TYPE,CAR_ID DESC



