WITH TBL AS(SELECT *
            FROM(SELECT HISTORY_ID,CAR_ID, MAX(START_DATE)AS START_DATE, MAX(END_DATE)AS END_DATE
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY                                             
                GROUP BY CAR_ID)X
            WHERE START_DATE >= DATE("2022-11-01") OR END_DATE <= DATE('2022-11-01'))

SELECT CAR_ID,CAR_TYPE,ROUND(DAILY_FEE*30*((100-DISCOUNT_RATE)/100),0) AS FEE

FROM TBL A NATURAL JOIN (SELECT *
                    FROM CAR_RENTAL_COMPANY_CAR 
                    WHERE CAR_TYPE='세단'OR CAR_TYPE='SUV')B

NATURAL JOIN

(SELECT *
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN 
WHERE DURATION_TYPE='30일 이상'
)C
WHERE (DAILY_FEE*((100-DISCOUNT_RATE)/100)*30 >=500000)AND(DAILY_FEE*((100-DISCOUNT_RATE)/100)*30 <2000000)

ORDER BY FEE DESC,CAR_TYPE,CAR_ID DESC  