-- 코드를 입력하세요
WITH TBL AS(SELECT *
FROM CART_PRODUCTS
WHERE NAME='Milk' OR NAME='Yogurt'
)

SELECT DISTINCT CART_ID
FROM TBL A JOIN TBL B
USING (CART_ID)
WHERE (A.NAME='Milk'and B.NAME='Yogurt')or(A.NAME='Yogurt'and B.NAME='Milk')
ORDER BY CART_ID