-- 코드를 입력하세요 
SELECT ANIMAL_ID,NAME
FROM(SELECT ANIMAL_INS.ANIMAL_ID,ANIMAL_INS.NAME,DATE_FORMAT(ANIMAL_INS.DATETIME,'%Y-%m-%d')AS X, DATE_FORMAT(ANIMAL_OUTS.DATETIME,'%Y-%m-%d')AS Y
    FROM ANIMAL_INS LEFT OUTER JOIN ANIMAL_OUTS
    ON ANIMAL_INS.ANIMAL_ID=ANIMAL_OUTS.ANIMAL_ID)Z
ORDER BY DATEDIFF(Y,X) DESC
LIMIT 2;


