-- 코드를 입력하세요
WITH TBL AS(
SELECT *,EXTRACT(YEAR FROM SALES_DATE)AS YEAR,EXTRACT(MONTH FROM SALES_DATE)AS MONTH
FROM ONLINE_SALE 
WHERE USER_ID IN(SELECT USER_ID
                FROM USER_INFO
                WHERE JOINED BETWEEN '2021-01-01'AND '2021-12-31')
),
TBL2 AS(SELECT YEAR,MONTH,COUNT(DISTINCT USER_ID)AS PURCHASED_USERS,(SELECT COUNT(USER_ID)
                                                FROM USER_INFO
                                                WHERE JOINED BETWEEN '2021-01-01'AND '2021-12-31') AS TOTAL
       FROM TBL
       GROUP BY YEAR,MONTH
       ORDER BY YEAR,MONTH)
       
SELECT YEAR,MONTH,PURCHASED_USERS,ROUND((PURCHASED_USERS/TOTAL),1) AS PURCHASED_RATIO
FROM TBL2


