-- 코드를 입력하세요

WITH TBL AS
(
	SELECT COUNT(*) AS TOTAL
FROM (SELECT *
FROM USER_INFO
WHERE JOINED LIKE '2021%'
GROUP BY USER_ID)X
)
SELECT EXTRACT(YEAR FROM SALES_DATE)AS YEAR,EXTRACT(MONTH FROM SALES_DATE)AS MONTH,
        COUNT(DISTINCT USER_ID)AS PUCHASED_USERS,ROUND(COUNT(DISTINCT USER_ID)/(SELECT * FROM TBL),1)AS PUCHASED_RATIO
FROM ONLINE_SALE 
WHERE USER_ID IN (SELECT USER_ID
                 FROM USER_INFO
                 WHERE JOINED LIKE '2021%')
GROUP BY YEAR,MONTH
ORDER BY YEAR,MONTH



