-- 코드를 입력하세요
WITH TBL AS(
SELECT *,YEAR(SALES_DATE)AS YEAR, MONTH(SALES_DATE)AS MONTH
FROM ONLINE_SALE 
WHERE USER_ID IN(
            SELECT USER_ID
            FROM USER_INFO 
            WHERE JOINED LIKE '2021%'))
            
SELECT YEAR,MONTH,COUNT(DISTINCT USER_ID)AS PURCHASED_USERS,ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(*)AS COUNTS
                                    FROM USER_INFO 
                                    WHERE JOINED LIKE '2021%'),1) AS PURCHASED_RATIO
FROM TBL
GROUP BY YEAR,MONTH
ORDER BY YEAR,MONTH

