-- 코드를 입력하세요
WITH TBL AS(
SELECT *,EXTRACT (MONTH FROM START_DATE) AS MONTH
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'),

TBL2 AS(
SELECT MONTH,CAR_ID,COUNT(*) AS RECORDS
FROM TBL
WHERE CAR_ID IN (
                SELECT CAR_ID
                FROM TBL
                GROUP BY CAR_ID
                HAVING COUNT(*)>=5)
GROUP BY MONTH,CAR_ID)

SELECT *
FROM TBL2 
WHERE RECORDS >0
ORDER BY MONTH,CAR_ID DESC