-- 코드를 입력하세요
WITH TBL AS(SELECT *
        FROM USED_GOODS_BOARD 
        ORDER BY VIEWS DESC
        LIMIT 1)

SELECT CONCAT('/home/grep/src/',BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT)AS FILE_PATH
FROM USED_GOODS_FILE INNER JOIN TBL
USING (BOARD_ID)
ORDER BY FILE_ID DESC