-- 코드를 입력하세요
WITH RECURSIVE CTE AS(
    SELECT 0 AS HOUR # 초기값 설정
    UNION ALL
    SELECT HOUR+1 FROM CTE
    WHERE HOUR < 23 # 반복을 멈추는 조건
)
SELECT A.HOUR, 
    CASE WHEN FIRST IS NULL THEN 0 ELSE FIRST END AS COUNT
FROM CTE A 
LEFT OUTER JOIN 
(SELECT *,EXTRACT(HOUR FROM DATETIME)AS HOUR,COUNT(ANIMAL_ID)AS FIRST
FROM ANIMAL_OUTS

GROUP BY HOUR)X
ON A.HOUR=X.HOUR
GROUP BY A.HOUR
ORDER BY A.HOUR