-- 코드를 입력하세요
WITH RECURSIVE CTE AS(
    SELECT 0 AS HOUR #시작값
    
    UNION ALL
    
    SELECT HOUR +1 
    FROM CTE
    WHERE HOUR<23),
    
TBL AS (SELECT EXTRACT(HOUR FROM DATETIME)AS HOUR
FROM ANIMAL_OUTS),

TBL2 AS (SELECT *,COUNT(HOUR) AS COUNT
FROM TBL
GROUP BY HOUR)

SELECT CTE.HOUR,IF(TBL2.COUNT IS NULL,0,TBL2.COUNT)AS 'COUNT'
FROM CTE LEFT OUTER JOIN TBL2
ON CTE.HOUR=TBL2.HOUR
ORDER BY CTE.HOUR

