-- 코드를 입력하세요
WITH TBL AS(SELECT WRITER_ID,COUNT(WRITER_ID) AS COUNTS
FROM USED_GOODS_BOARD
GROUP BY WRITER_ID),

TBL2 AS (SELECT *
    FROM TBL INNER JOIN USED_GOODS_BOARD
    USING (WRITER_ID)
    WHERE COUNTS>=3)

SELECT DISTINCT B.USER_ID,B.NICKNAME,CONCAT(B.CITY,' ',B.STREET_ADDRESS1,' ',STREET_ADDRESS2)AS '전체주소',
CONCAT(LEFT(TLNO,3),'-',SUBSTR(TLNO,4,4),'-',RIGHT(TLNO,4))AS '전화번호'
FROM TBL2 A LEFT OUTER JOIN USED_GOODS_USER B
ON A.WRITER_ID=B.USER_ID	
ORDER BY B.USER_ID DESC
