-- 코드를 입력하세요
SELECT CAR_ID,ROUND(AVG(P),1) AS AVERAGE_DURATION

FROM(SELECT CAR_ID, START_DATE,END_DATE,DATEDIFF(END_DATE,START_DATE)+1 AS P
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY) X
GROUP BY CAR_ID
HAVING AVG(P)>=7
ORDER BY AVERAGE_DURATION DESC,CAR_ID DESC

