-- 코드를 입력하세요
SELECT X.FLAVOR
FROM (SELECT FLAVOR,SUM(TOTAL_ORDER) AS FIRST_HALF_TOTAL
    FROM FIRST_HALF
    GROUP BY FLAVOR)X INNER JOIN (SELECT FLAVOR,SUM(TOTAL_ORDER)AS JULY_TOTAL
                            FROM JULY
                            GROUP BY FLAVOR)Y
ON X.FLAVOR=Y.FLAVOR
ORDER BY FIRST_HALF_TOTAL+JULY_TOTAL DESC
LIMIT 3
