-- 코드를 입력하세요
WITH TBL AS (SELECT WRITER_ID,SUM(PRICE) AS 'TOTAL_SALES'
FROM USED_GOODS_BOARD 
WHERE STATUS='DONE' 
GROUP BY WRITER_ID)

SELECT USED_GOODS_USER.USER_ID,USED_GOODS_USER.NICKNAME,TBL.TOTAL_SALES
FROM USED_GOODS_USER INNER JOIN TBL
ON USER_ID=WRITER_ID
WHERE TOTAL_SALES>=700000
ORDER BY TOTAL_SALES 