-- 코드를 입력하세요
WITH TBL AS 
(SELECT A.MEMBER_ID,A.MEMBER_NAME,B.REVIEW_TEXT,B.REVIEW_DATE,COUNT(B.MEMBER_ID) AS COUNTS
FROM MEMBER_PROFILE A RIGHT OUTER JOIN REST_REVIEW B
ON A.MEMBER_ID=B.MEMBER_ID
GROUP BY B.MEMBER_ID
ORDER BY COUNTS DESC
LIMIT 1)

# TBL2 AS
#(SELECT MEMBER_ID,MEMBER_NAME,REVIEW_TEXT,REVIEW_DATE,MAX(COUNTS)
#FROM TBL)

SELECT A.MEMBER_NAME,B.REVIEW_TEXT,DATE_FORMAT(B.REVIEW_DATE,'%Y-%m-%d')AS REVIEW_DATE
FROM MEMBER_PROFILE A RIGHT OUTER JOIN REST_REVIEW B
ON A.MEMBER_ID=B.MEMBER_ID
WHERE B.MEMBER_ID IN (SELECT MEMBER_ID
                    FROM TBL)
ORDER BY REVIEW_DATE, REVIEW_TEXT