-- 코드를 입력하세요
SELECT REAL_PRICE*10000 AS PRICE_GROUP, COUNT(REAL_PRICE) AS PRODUCTS
FROM(SELECT *, CASE 
            WHEN PRICE IS NOT NULL 
            THEN TRUNCATE(PRICE / 10000,0) END AS REAL_PRICE
        FROM PRODUCT ) X
GROUP BY REAL_PRICE
ORDER BY PRICE_GROUP

