-- 코드를 입력하세요
WITH TBL AS(
    SELECT A.BOOK_ID,C.AUTHOR_ID,C.AUTHOR_NAME,B.CATEGORY,SUM(A.SALES)*B.PRICE AS TOTAL_SALES

FROM BOOK_SALES A 
LEFT OUTER JOIN BOOK B
ON A.BOOK_ID=B.BOOK_ID
LEFT OUTER JOIN AUTHOR C
ON B.AUTHOR_ID=C.AUTHOR_ID

WHERE A.SALES_DATE LIKE "2022-01%"

GROUP BY A.BOOK_ID
)
SELECT AUTHOR_ID,AUTHOR_NAME,CATEGORY,SUM(TOTAL_SALES)AS TOTAL_SALES

FROM TBL
GROUP BY AUTHOR_ID,CATEGORY
ORDER BY AUTHOR_ID,CATEGORY DESC