-- 코드를 입력하세요
SELECT A.AUTHOR_ID,A.AUTHOR_NAME,B.CATEGORY,SUM(C.SALES*B.PRICE) AS TOTAL_SALES
    FROM 
    AUTHOR A 
    inner JOIN BOOK B
    ON A.AUTHOR_ID=B.AUTHOR_ID
    inner JOIN BOOK_SALES C
    ON B.BOOK_ID=C.BOOK_ID
     
    WHERE SALES_DATE LIKE '2022-01%'

    
GROUP BY AUTHOR_ID,CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC