-- 코드를 입력하 세요
WITH TBL AS(
SELECT product_code,sales_amount*price AS SALES
FROM OFFLINE_SALE LEFT OUTER JOIN PRODUCT
USING (PRODUCT_ID)
)

SELECT product_code,SUM(SALES) AS SALES
FROM TBL
GROUP BY product_code
ORDER BY SALES DESC, product_code