-- 코드를 입력하세요
WITH TBL AS (SELECT *
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                WHERE CAR_ID IN(SELECT CAR_ID
                                FROM CAR_RENTAL_COMPANY_CAR 
                                WHERE CAR_TYPE='트럭')),
TBL2 AS(SELECT A.HISTORY_ID,A.CAR_ID,B.DAILY_FEE,DATEDIFF(END_DATE,START_DATE)+1 AS RENT_DAYS
            FROM TBL A LEFT OUTER JOIN CAR_RENTAL_COMPANY_CAR B
            ON A.CAR_ID=B.CAR_ID),
            

TBL3 AS (SELECT *,
        CASE WHEN (RENT_DAYS>=7) & (RENT_DAYS<30) THEN 5
            WHEN (RENT_DAYS>=30) & (RENT_DAYS<90) THEN 8
            WHEN RENT_DAYS>=90 THEN 15 ELSE 0 END AS RATE
        FROM TBL2)
SELECT HISTORY_ID,ROUND(DAILY_FEE*((100-RATE)/100)*RENT_DAYS,0) AS FEE
FROM TBL3
ORDER BY FEE DESC,HISTORY_ID DESC