-- 코드를 입력하세요
SELECT B.APNT_NO,A.PT_NAME,A.PT_NO,B.MCDP_CD,C.DR_NAME,APNT_YMD
FROM 
(PATIENT A 
RIGHT OUTER JOIN 
APPOINTMENT B
ON (A.PT_NO=B.PT_NO)

LEFT OUTER JOIN DOCTOR C
ON B.MDDR_ID=C.DR_ID)

WHERE APNT_YMD LIKE'2022-04-13%' AND APNT_CNCL_YN='N' AND B.MCDP_CD='CS'
ORDER BY APNT_YMD