-- 코드를 입력하세요
WITH TBL AS(SELECT *
FROM APPOINTMENT 
WHERE APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN='N'),

TBL2 AS(SELECT *
FROM TBL INNER JOIN PATIENT 
USING (PT_NO)),

TBL3 AS(SELECT A.PT_NO,A.PT_NAME,A.APNT_YMD,A.APNT_NO,A.MCDP_CD,B.DR_NAME
FROM TBL2 A INNER JOIN DOCTOR B
ON A.MDDR_ID=B.DR_ID)

SELECT APNT_NO,PT_NAME,PT_NO,MCDP_CD,DR_NAME,APNT_YMD
FROM TBL3
ORDER BY APNT_YMD

