-- 코드를 입력하세요
WITH TBL AS (SELECT REST_ID,REST_INFO.REST_NAME,REST_INFO.FOOD_TYPE	,REST_INFO.FAVORITES,REST_INFO.ADDRESS,REST_REVIEW.REVIEW_SCORE
FROM REST_REVIEW LEFT OUTER JOIN REST_INFO 
USING (REST_ID)
WHERE ADDRESS LIKE '서울%')

SELECT REST_ID,REST_NAME,FOOD_TYPE,FAVORITES,ADDRESS,ROUND(AVG(REVIEW_SCORE),2)AS SCORE
FROM TBL
GROUP BY REST_ID
ORDER BY SCORE DESC,FAVORITES DESC