-- 코드를 입력하세요
SELECT A.REST_ID,A.REST_NAME,A.FOOD_TYPE,A.FAVORITES,A.ADDRESS,X.REVIEW_SCORE AS SCORE

FROM REST_INFO A JOIN (SELECT A.REST_ID,ROUND(AVG(B.REVIEW_SCORE),2)AS REVIEW_SCORE
                    FROM REST_INFO A LEFT OUTER JOIN REST_REVIEW B
                    ON A.REST_ID=B.REST_ID
                    WHERE ADDRESS LIKE '서울%' AND REVIEW_SCORE IS NOT NULL
                    GROUP BY REST_ID)X
ON A.REST_ID=X.REST_ID

ORDER BY SCORE DESC,A.FAVORITES DESC

